### PR TITLE
Fix for iOS where the implementation is null.

### PR DESCRIPTION
**Pull request by foppenm**
Fix for iOS where the implementation is null. The this.Activiated (in AbstractNotificationsImpl.cs line 35) is another/not the instance that the event is registered to. The Activated event is now triggered for iOS in the sample app.

### CODE REVIEW

**Comment by aritchie** [comment]
Thank you for the PR.  I don't actually see anything that fixes the activated event in your PR unless I overlooked something.

I'm also not willing to take the factory implementations as they simply aren't necessary and will create confusion for others.  CrossNotifications.Current deals with the bait & switch.  iOS uses a wrapper to swap implementations based on version.  If people want the ability to create their own implementations, they can simply use CrossNotifications.Current = <your implementation>;

**Comment by foppenm** [comment]
Thanks for the comment. The reason why it is not working on iOS is because the CrossNotifications.Current is the implementation that the Activated event registered on. On iOS the event should be registered on CrossNotification.Current.imp. That is the readonly field and only in the iOS implementation. With the factory I tried to make CrossNotification.Current the right implementatation.

To reproduce this situation:
- Debug the solution for iOS platform
- Tap "Press This & Exit App within 10 seconds"
- Exit the app
- Set breakpoint on AbstractNotificationImpl.cs line 35
- Tap the notification on iOS.
- this.Activated is null.

In the last step if you get the this.GetHashCode() and compare it with CrossNotifications.Current, you will see that it is not the same implementation.

If you want to test this you can always get the solution from: https://github.com/foppenm/notifications

**Comment by aritchie** [comment]
I have fixed the original implementation and released to nuget.  I appreciate the help in fixing this though.

**Comment by foppenm** [comment]
No problem, thanks for the quick nuget!

**Pull request closed without merging**
