### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by eplewis89**
Please pull dev branch into master and release code to nuget
New xamarin android version will NOT work with your current nuget package.

### CODE REVIEW

**Comment by eplewis89** [comment]
FYI I pulled your current master which is on #e691af and updated the Xamarin.Android.Support.v4 to latest version and the project builds, even if you don't release the dev branch, please consider rebuilding the master with the updated android support library

I'd appreciate a timely response to this :)

**Comment by aritchie** [comment]
Please note that I do not support this library right now and this is the reason issues has been disabled.

**Comment by FrozenKiwi** [comment]
Hi Mr Ritchie.

I've been using this library for a while, and am curious as to your future plans for it.

For my own project, I tried to switch over to a similar library - but ended up forking and coming back to this library because it's still the best answer to the notification question.

If you received some assistance maintaining this library, would you consider re-publishing it?  I'm expecting to continue actively developing a project with this library for several years, and it seems wasteful to let such an excellent package drop out of the way.

Sorry for necro-ing the thread, but I can't create new issues, and this seemed the most appropriate way to contact you.

Cheers,
Steve T

**Comment by bbl-Laobu** [comment]
I have a similar request as Steve T.
What would it take for you to maintain this library as indeed it is indeed the only descent one out there?

Thanks,
B

**Comment by aritchie** [comment]
@FrozenKiwi @bbl-Laobu As I said above, I'm not supporting this library right now.  That is why issues have been disabled.  This library has been moved to a larger effort anyhow at https://github.com/shinyorg/shiny which is in beta right now

**Pull request closed without merging**
